### ISSUE TITLE
Crash reading CML files

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1060]
Program received signal SIGSEGV, Segmentation fault.
0xb55e11c7 in OpenBabel::XMLConversion::ReadStream(void*, char*, int) () from /usr/lib/openbabel/2.2.3/cmlformat.so
(gdb) bt
#0  0xb55e11c7 in OpenBabel::XMLConversion::ReadStream(void*, char*, int) () from /usr/lib/openbabel/2.2.3/cmlformat.so
#1  0xb5e959fc in xmlParserInputBufferGrow () from /usr/lib/libxml2.so.2
#2  0xb5f1b7e0 in xmlTextReaderSetup () from /usr/lib/libxml2.so.2
#3  0xb55e251c in OpenBabel::XMLConversion::GetDerived(OpenBabel::OBConversion*, bool) () from /usr/lib/openbabel/2.2.3/cmlformat.so
#4  0xb55dbd02 in OpenBabel::XMLMoleculeFormat::ReadMolecule(OpenBabel::OBBase*, OpenBabel::OBConversion*) () from /usr/lib/openbabel/2.2.3/cmlformat.so
#5  0xb7e9c011 in OpenBabel::OBConversion::Read(OpenBabel::OBBase*, std::istream*) () from /usr/lib/libopenbabel.so.3
#6  0xb7e9c37e in OpenBabel::OBConversion::ReadFile(OpenBabel::OBBase*, std::string) () from /usr/lib/libopenbabel.so.3
#7  0x0804d21e in MainWindow::MainWindow(QWidget*) ()
#8  0x0804bcf5 in main (argc=1, argv=0xbffff564) at main.cpp:7

You can find my code including the cml-files here:
http://gitorious.org/molecules

Reported by: @cniehaus

**Comment by serval2412** [comment]
gitorious.org/molecules/molecules/trees/master/data doesn't seem to respond.
Would it be possible to attach a cml file with a command line which triggers the crash so it can be quick and easy to reproduce?
