### ISSUE TITLE
Install the python-binding into virutalenv.

### ISSUE THREAD

**Issue by hongyi-zhao** [openbabel/openbabel#2137]
Hi,

I try to compile the openbabel with python-binding as following for my python virtualenv:

```
$ git clone https://github.com/openbabel/openbabel.git openbabel.git
$ cd openbabel.git
$ mkdir build 
$ cd build 
$ pyenv shell hpc
$ cmake ../ -DPYTHON_EXECUTABLE=$(pyenv which python) -DPYTHON_BINDINGS=ON -DRUN_SWIG=ON
$ sudo make install
```

But this will install the python oenbabel bindings into the following location:

```
-- Installing: /usr/local/lib/python3.8/site-packages/openbabel/_openbabel.so
-- Set runtime path of "/usr/local/lib/python3.8/site-packages/openbabel/_openbabel.so" to "/usr/local/lib"
-- Installing: /usr/local/lib/python3.8/site-packages/openbabel/__init__.py
-- Installing: /usr/local/lib/python3.8/site-packages/openbabel/openbabel.py
-- Installing: /usr/local/lib/python3.8/site-packages/openbabel/pybel.py
```

I want to let the python binding be installed into the virtualenv's site-packages diretory, how should I config the cmake?

Regards

**Comment by mcs07** [comment]
You can try `-DPYTHON_BINDINGS=OFF -DRUN_SWIG=OFF` and then afterwards run `pip install openbabel`. But it is not well supported. Consider using a conda environment instead of virualenv, then you can just do `conda install openbabel`.

**Comment by hongyi-zhao** [comment]
> -DPYTHON_BINDINGS=OFF -DRUN_SWIG=OFF

With you method, just as I've told in another thread, the pip install will use the older version of openbabel, instead of the latest version found on the pypi:

```
$ pip install openbabel
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting openbabel
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9c/30/eb9c3d3d3b86981f6c6a7b8eceb6f4a13b9a12673efbc842b7cebe0ce39a/openbabel-2.4.1.tar.gz (74kB)
     |████████████████████████████████| 81kB 6.4MB/s 
Installing collected packages: openbabel
  Running setup.py install for openbabel ... /^canceled
```

I want to install the python binding shipped in the source-code and compile by me.

Regards

**Comment by mcs07** [comment]
Ah then maybe you can do `cd ../scripts/python` then `python setup.py install`

**Comment by hongyi-zhao** [comment]
> python setup.py install

See the following:

```
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 22, in find_version
    with open(os.path.join(base_dir, 'openbabel', '__init__.py')) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/werner/Public/hpc/tools/openbabel.git/scripts/python/openbabel/__init__.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 119, in <module>
    version=find_version(),
  File "setup.py", line 29, in find_version
    raise Exception('Could not find openbabel/__init__.py.')
Exception: Could not find openbabel/__init__.py.

```

**Comment by mcs07** [comment]
Ah yes... it now requires cmake to be run with `-DPYTHON_BINDINGS=ON` to generate the `__init__.py` file... If you are happy to ignore the files being installed to `/usr/local/lib/python3.8/` you could do that? Then run `python setup.py install` in your virtualenv.

Otherwise, manually copy `scripts/python/__init__.py.in` to `scripts/python/__init__.py` and change line 5 to `__version__ = "3.0.0"`.

As you can see, this isn't well supported and may have other issues...

**Comment by hongyi-zhao** [comment]
Thanks a lot, got it.  See the following for the detail steps:

```
$ cd openbabel.git
# The pyenv-based virtubalenv used by me to do the job:
$ pyenv shell hpc
# Must use -DPYTHON_BINDINGS=ON -DRUN_SWIG=ON, otherwise will meet errors and 
# the scripts/python/__init__.py won't be created:
$ cmake ../ -DPYTHON_EXECUTABLE=$(pyenv which python) -DPYTHON_BINDINGS=ON -DRUN_SWIG=ON -DBUILD_GUI=ON
$ make -j24
# This will install the python binding into /usr/local/lib, let me hack it for installing it into the user's 
# currently activated virtualenv:
$ sudo make install

# Now install the python binding into the currently activated virtualenv:
$ cd scripts/python
#  The following files must be put into the openbabel directory:
$ cp ../stereo.i ../openbabel-python.i openbabel/
# Finally do the job, any of the following commands will do the job:
$ pip install -e .
or
$ pip install
or
$ python setup.py install
```


Say, for using the following command, see the output obtained by me:
 
```
$ pip install -e .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/werner/Public/hpc/tools/openbabel.git/scripts/python
Installing collected packages: openbabel
  Attempting uninstall: openbabel
    Found existing installation: openbabel 3.0.0
    Uninstalling openbabel-3.0.0:
      Successfully uninstalled openbabel-3.0.0
  Running setup.py develop for openbabel
Successfully installed openbabel
```

PS.  I love anaconda/miniconda also, but still want to do the job by cpython.  The conda-based workflow seems have the following shortcommings:

- Ofter too slow for running the SAT solver to find the requirements' packages list for the environment.
- Maybe problematic for mixing the usage of pip and conda to install packages. 
- All of the packages are per-compiled.

Regards
