### ISSUE TITLE
 Symbol not found: __ZN9OpenBabel9aromtyperE

### ISSUE THREAD

**Issue by mabianchet** [openbabel/openbabel#2244]
- [ x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 3.1.1
Operating system and version: MacOS Mojave

## Expected Behavior
python3 -c  'import openbabel'  

## Actual Behavior

python3 -c 'import openbabel'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/openbabel/__init__.py", line 3, in <module>
    from . import openbabel
  File "/usr/local/lib/python3.8/site-packages/openbabel/openbabel.py", line 22, in <module>
    from . import _openbabel
ImportError: dlopen(/usr/local/lib/python3.8/site-packages/openbabel/_openbabel.cpython-38-darwin.so, 2): Symbol not found: __ZN9OpenBabel9aromtyperE
  Referenced from: /usr/local/lib/python3.8/site-packages/openbabel/_openbabel.cpython-38-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.8/site-packages/openbabel/_openbabel.cpython-38-darwin.so

## Steps to Reproduce
python3 -c 'import openbabel'

**Comment by ghutchis** [comment]
Using Open Babel >3.0, this is not how you import the Python module. My guess is that you also have an old version installed.

https://open-babel.readthedocs.io/en/latest/UseTheLibrary/migration.html

`from openbabel import openbabel`

**Comment by mabianchet** [comment]
Thanks ghutchis. I believed were equivalents but anyway...

Python 3.8.3 (default, May 27 2020, 20:53:40) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from openbabel import openbabel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/openbabel/__init__.py", line 3, in <module>
    from . import openbabel
  File "/usr/local/lib/python3.8/site-packages/openbabel/openbabel.py", line 22, in <module>
    from . import _openbabel
ImportError: dlopen(/usr/local/lib/python3.8/site-packages/openbabel/_openbabel.cpython-38-darwin.so, 2): Symbol not found: __ZN9OpenBabel9aromtyperE
  Referenced from: /usr/local/lib/python3.8/site-packages/openbabel/_openbabel.cpython-38-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.8/site-packages/openbabel/_openbabel.cpython-38-darwin.so
>>>

**Comment by mabianchet** [comment]
I installed it using conda,  brew , pip3 and brew from source and i am built it with the same result. ANy hint in where to look to fixed will be appreciate.

This may said something

Using python3 -v
>>> from openbabel import openbabel
# /usr/local/lib/python3.8/site-packages/openbabel/__pycache__/__init__.cpython-38.pyc matches /usr/local/lib/python3.8/site-packages/openbabel/__init__.py
# code object from '/usr/local/lib/python3.8/site-packages/openbabel/__pycache__/__init__.cpython-38.pyc'
# /usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/__pycache__/warnings.cpython-38.pyc matches /usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/warnings.py
# code object from '/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/__pycache__/warnings.cpython-38.pyc'
import 'warnings' # <_frozen_importlib_external.SourceFileLoader object at 0x10d9f75b0>
# /usr/local/lib/python3.8/site-packages/openbabel/__pycache__/openbabel.cpython-38.pyc matches /usr/local/lib/python3.8/site-packages/openbabel/openbabel.py
# code object from '/usr/local/lib/python3.8/site-packages/openbabel/__pycache__/openbabel.cpython-38.pyc'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/openbabel/__init__.py", line 3, in <module>
    from . import openbabel
  File "<frozen importlib._bootstrap>", line 1042, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/openbabel/openbabel.py", line 22, in <module>
    from . import _openbabel
  File "<frozen importlib._bootstrap>", line 1042, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(/usr/local/lib/python3.8/site-packages/openbabel/_openbabel.cpython-38-darwin.so, 2): Symbol not found: __ZN9OpenBabel9aromtyperE
  Referenced from: /usr/local/lib/python3.8/site-packages/openbabel/_openbabel.cpython-38-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.8/site-packages/openbabel/_openbabel.cpython-38-darwin.so
>>>

**Comment by ghutchis** [comment]
You clearly have multiple versions of Python on your system. I don't know what version of Python you're using or what installed `openbabel`. I know that neither the source package, or `conda-forge` would install a _openbabel.cpython-38-darwin.so file, which is clearly from an old binary.

I personally recommend using anaconda, which IIRC installs into a separate path, e.g. `/usr/local/anaconda/bin/python`

The `conda-forge` channel is updated within hours of a release:
`conda install -c conda-forge openbabel`

My suggestion for you would be to `rm -rf  /usr/local/lib/python3.8/site-packages/openbabel*` - that install is clearly linked to old Open Babel binaries.

**Comment by mabianchet** [comment]
Thanks, ghutchis
