### ISSUE TITLE
testobconv_writers test failure on arm64 and ppc64el

### ISSUE THREAD

**Issue by LocutusOfBorg** [openbabel/openbabel#2246]
- [X] I believe this to be a bug with Open Babel

## Environment Information
Open Babel version: 3.1.1 + commit 7de27f309db5f7ec026ef5c5235e5b33bf7d1a85
Operating system and version:
Ubuntu 20.10 development release

## Expected Behavior
Test succeed on arm64 and ppc64el

## Actual Behavior
```
Running test/testobconv_writers.py ...
..........................................................................................F..................................................
======================================================================
FAIL: test_default (__main__.TestPCJSON)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/testobconv_writers.py", line 2761, in test_default
    self.assertWriters(self.fmt, """\
  File "test/testobconv_writers.py", line 258, in assertWriters
    test_write_string(self, mol, conv, expected_output, normalize)
  File "test/testobconv_writers.py", line 165, in test_write_string
    test_case.assertMultiLineEqual(output.replace("\r\n", "\n"), expected_output.replace("\r\n", "\n"))
AssertionError: '{\n [1926 chars]102014\n              ],\n              "y": [[1070 chars]]\n}' != '{\n [1926 chars]102012\n              ],\n              "y": [[1070 chars]]\n}'
  {
    "PC_Compounds": [
      {
        "atoms": {
          "aids": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13
          ],
          "element": [
            6,
            6,
            6,
            6,
            6,
            6,
            8,
            1,
            1,
            1,
            1,
            1,
            1
          ]
        },
        "bonds": {
          "aid1": [
            1,
            1,
            2,
            3,
            4,
            5,
            6,
            1,
            2,
            3,
            4,
            5,
            7
          ],
          "aid2": [
            6,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13
          ],
          "order": [
            2,
            1,
            2,
            1,
            2,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
          ]
        },
        "coords": [
          {
            "type": [
              1
            ],
            "aids": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "conformers": [
              {
                "x": [
                  1.5846,
                  1.5703,
                  2.4295,
                  3.3031,
                  3.3175,
                  0.0,
                  -1.0005,
                  2.313816216007316,
                  0.669250157347277,
                  2.4146659588503769,
                  4.189331679349326,
                  4.052466878708012,
-                 -1.4648575597102014
?                                   ^
+                 -1.4648575597102012
?                                   ^
                ],
                "y": [
                  1.5846,
                  1.5703,
                  2.4295,
                  3.3031,
                  3.3175,
                  0.0,
                  -1.0005,
                  2.313816216007316,
                  0.669250157347277,
                  2.4146659588503769,
                  4.189331679349326,
                  4.052466878708012,
-                 -1.4648575597102014
?                                   ^
+                 -1.4648575597102012
?                                   ^
                ],
                "style": {
                  "annotation": [
                    8,
                    8,
                    8,
                    8,
                    8,
                    8
                  ],
                  "aid1": [
                    1,
                    1,
                    2,
                    3,
                    4,
                    5
                  ],
                  "aid2": [
                    6,
                    2,
                    3,
                    4,
                    5,
                    6
                  ]
                }
              }
            ]
          }
        ],
        "charge": 0
      }
    ]
  }

```

## Steps to Reproduce
See e.g.:
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy/groovy/arm64/o/openbabel/20200603_115438_23a53@/log.gz
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy/groovy/ppc64el/o/openbabel/20200603_110529_77a4e@/log.gz

Also test/testbindings.py and test/testsym.py have issues on non-amd64 platforms.

**Comment by boegel** [comment]
This problem doesn't only manifest on `arm64` or `ppc64le`, I'm seeing the exact same test failure on Intel Haswell and AMD Rome (zen2).

I've worked around this by applying the following patch, under the assumption that this is OK to do (strictly comparing floating-point values doesn't seem like a good approach to me in general):

```diff
--- openbabel-openbabel-3-1-1/test/testobconv_writers.py.orig	2022-01-12 20:12:01.480069896 +0100
+++ openbabel-openbabel-3-1-1/test/testobconv_writers.py	2022-01-12 20:12:12.180174159 +0100
@@ -2876,7 +2876,7 @@
                 2.4146659588503769,
                 4.189331679349326,
                 4.052466878708012,
-                -1.4648575597102012
+                -1.4648575597102014
               ],
               "y": [
                 1.5846,
@@ -2891,7 +2891,7 @@
                 2.4146659588503769,
                 4.189331679349326,
                 4.052466878708012,
-                -1.4648575597102012
+                -1.4648575597102014
               ],
               "style": {
                 "annotation": [

**Comment by LocutusOfBorg** [comment]
@boegel sadly this patch fixes the build for arm64 and ppc64el, and breaks the build for other architectures :D
We should probably relax the precision for that last digit...

**Comment by boegel** [comment]
@LocutusOfBorg With this patch, it worked fine for me on various `x86_64` systems. It's probably more tied to the compiler.

But yes, relaxing the required precision a bit would still fix that.
Strictly comparing floating-point values is a bad idea in general anyway :)
