### ISSUE TITLE
Exception after importing openbabel in Python

### ISSUE THREAD

**Issue by edmondo1984** [openbabel/openbabel#2413]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 3.1.1
Operating system and version: ProductName:    macOS
ProductVersion: 11.5.2

## Expected Behavior

I have worked around #2412 by adding to my Makefile a custom pip installation:

```pip install --global-option=build_ext --global-option="-I$(openbabel_include_version)" --global-option="-L$(openbabel_library_version)" openbabel```

and I was able to install correctly openbabel Python bindings. However, when I import it in a python shell:

```
>>> import openbabel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/myusername/Library/Caches/pypoetry/virtualenvs/my-project-AqK3HHEa-py3.9/lib/python3.9/site-packages/openbabel/__init__.py", line 3, in <module>
    from . import openbabel
  File "/Users/myusername/Library/Caches/pypoetry/virtualenvs/my-project-AqK3HHEa-py3.9/lib/python3.9/site-packages/openbabel/openbabel.py", line 22, in <module>
    from . import _openbabel
ImportError: dlopen(/Users/myusername/Library/Caches/pypoetry/virtualenvs/my-project-AqK3HHEa-py3.9/lib/python3.9/site-packages/openbabel/_openbabel.cpython-39-darwin.so, 2): Symbol not found: __ZN9OpenBabel9aromtyperE
  Referenced from: /Users/myusername/Library/Caches/pypoetry/virtualenvs/my-project-AqK3HHEa-py3.9/lib/python3.9/site-packages/openbabel/_openbabel.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/myusername/Library/Caches/pypoetry/virtualenvs/my-project-AqK3HHEa-py3.9/lib/python3.9/site-packages/openbabel/_openbabel.cpython-39-darwin.so
```

## Steps to Reproduce

- Install open-babel and swig via brew
- Install openbabel python bindings via PIP as suggested
- launch python and import openbabel

**Comment by ghutchis** [comment]
You're either not linking to the right `libopenbabel` from your compile.

What does `otool -L /Users/myusername/Library/Caches/pypoetry/virtualenvs/my-project-AqK3HHEa-py3.9/lib/python3.9/site-packages/openbabel/_openbabel.cpython-39-darwin.so` report?

**Comment by edmondo1984** [comment]
Thanks a lot for your help! That's the result

```
        /opt/homebrew/opt/open-babel/lib/libopenbabel.7.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 905.6.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
```

**Comment by seanharr11** [comment]
One solution is to add the global `site-packages` path to your `PYTHONPATH` before starting your `python` interpreter. E.g. `export PYTHONPATH=/usr/local/lib/python3.9/site-packages:$PYTHONPATH`

To my knowledge, there is no clean way to install openbabel to a virtual `env` with the current tools available (`brew` and `pip`). Any suggestions for how we could support this? It appears the package is meant to be installed globally, but not as a project dependency.

**Comment by timothygebhard** [comment]
I can confirm that @seanharr11's solution fixes the problem for me! :)

Another way that seems to work is to use a symlink from the `site-packages` directory of your virtualenv to the global installation, i.e., something like this:
```
ln -s /usr/local/lib/python3.9/site-packages/openbabel ~/.virtualenvs/<name>/lib/python3.9/site-packages/openbabel
```
That way, I can't forget to add the package to the `PYTHONPATH`, and I don't need to add the `export` command to my `.zshrc`, where it would affect _all_ virtualenvs that I am working with (even the ones where I don't need openbabel).

**Comment by widcardw** [comment]
Hello, I am using miniconda and installed OpenBabel with `conda install -c conda-forge openbabel`. Then I install SWIG with brew, and install openbabel dependencies with

```sh
pip install -U openbabel --global-option=build_ext \
--global-option="-I/Users/myname/miniconda3/envs/py38/include/openbabel3" \
--global-option="-L/Users/myname/miniconda3/envs/py38/lib/openbabel"
```

In my virtual env, the code hint seems to work.

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/55699713/223072740-2818dded-03dd-418e-9008-cbbdf802249a.png">

However, when I execute the code, it raises errors.

```sh
$ python src/test_pybel.py
Traceback (most recent call last):
  File "src/test_pybel.py", line 16, in <module>
    from openbabel import openbabel
  File "/Users/myname/Desktop/openbabel/plba/lib/python3.8/site-packages/openbabel/__init__.py", line 3, in <module>
    from . import openbabel
  File "/Users/myname/Desktop/openbabel/plba/lib/python3.8/site-packages/openbabel/openbabel.py", line 22, in <module>
    from . import _openbabel
ImportError: dlopen(/Users/myname/Desktop/openbabel/plba/lib/python3.8/site-packages/openbabel/_openbabel.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '__ZN9OpenBabel9aromtyperE'
```

And just simply importing openbabel like `from openbabel import openbabel` also raises errors. How to solve this? Thx!

**Comment by fredrikw** [comment]
Hello,

It seems from your description that you install OpenBabel twice, in different ways. That will most likely lead to a bunch of problems. If you install openbabel via Conda you shouldn't need to install it again via pip. So remove your conda environment and retry without the pip step.

**Comment by widcardw** [comment]
> 

Thanks for your suggestion. I've solved this problem. Maybe I don't need a virtualenv, using conda environment is ok `¯\_(ツ)_/¯`
