### ISSUE TITLE
installing openbabel with Python bindings

### ISSUE THREAD

**Issue by Rojaettfolk** [openbabel/openbabel#2524]
Hi, I am trying to run a script for generating slabs and I use pymatgen and openbeabel at some point. But I get this error:

------------------
           Writing surface slab to Anatase_101_T2_Ti120_O240.pdb...
Traceback (most recent call last):
  File "slabs_generate_surface_slab.py", line 189, in <module>
    sys.exit(main())
  File "slabs_generate_surface_slab.py", line 163, in main
    pdb_file = system.to("pdb")
  File "/home/rora1983/.local/lib/python3.8/site-packages/pymatgen/core/structure.py", line 2732, in to
    writer = BabelMolAdaptor(self)
  File "/home/rora1983/.local/lib/python3.8/site-packages/monty/dev.py", line 96, in decorated
    raise RuntimeError(self.message)
RuntimeError: BabelMolAdaptor requires openbabel to be installed with Python bindings. Please get it at http://openbabel.org.
-----------------
As far as I understood I need to somehow recompile the openbabel with python bindins and I get this error:
--------------------
-- Using included inchi library.
-- Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES wxWidgets_INCLUDE_DIRS) 
-- Checking available shared pointer...
-- Use std::shared_ptr in memory
-- Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK) (Required is at least version "2.91.0")
-- Could NOT find Eigen2 (missing: EIGEN2_INCLUDE_DIR EIGEN2_VERSION_OK) (Required is at least version "2.0.0")
-- Checking for module 'cairo'
--   No package 'cairo' found
-- Could NOT find Cairo (missing: CAIRO_LIBRARIES CAIRO_INCLUDE_DIRS) 
-- Could NOT find Cairo. PNG output will NOT be supported.
-- Attempting to build the GUI
--    wxWidgets not found => GUI will not be built
-- Warning: Python bindings NOT found. Generate using -DRUN_SWIG.
-- Warning: Ruby bindings NOT found. Generate using -DRUN_SWIG.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rora1983/Downloads/obabel/build
--------------------
I tried to specify the python path several times and reinstall everything and so on but it doesn't work. I looked up for some previous discussions but I couldn't get it to work. Can anyone help me?

**Comment by fredrikw** [comment]
To start with, the actual error message says `-- Warning: Python bindings NOT found. Generate using -DRUN_SWIG.` regarding the Python bindings, so you need to rerun cmake with `-DRUN_SWIG`.

BUT, you also have a lot of other stuff missing according to cmake so you will have more things to add to get everything working fully. How did you install pymatgen? If you are using a conda environment, the easiest way (by far) to install OpenBabel is through  `conda install -c conda-forge openbabel`.
