### ISSUE TITLE
Seg faults with the smiley parser

### ISSUE THREAD

**Issue by jeffjanes** [openbabel/openbabel#294]
Attached is a file of SMILES, all taken from wikipedia articles with ChemBox template, which individually cause seg faults in the parser "obabel -ismy"

These SMILES cause warnings, but not segfaults, with the "obabel -ismi" parser.

[smy_parser_seg_fault.txt](https://github.com/openbabel/openbabel/files/198712/smy_parser_seg_fault.txt)

**Comment by ghutchis** [comment]
Thanks. It's not the default because it hasn't received the same level of testing.

**Comment by serval2412** [comment]
With master sources updated today, I could retrieve a bt:
Error: attempt to subscript container with out-of-bounds index 2147483647, 
but container only holds 24 elements.

Objects involved in the operation:
    sequence "this" @ 0x0x7fffffffc910 {
      type = std::__debug::vector<int, std::allocator<int> >;
    }

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: Aucun fichier ou dossier de ce type.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7a54231 in __GI_abort () at abort.c:79
#2  0x00007ffff667e4d5 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff730d5d9 in std::__debug::vector<int, std::allocator<int> >::operator[] (this=0x7fffffffc910, __n=2147483647) at /usr/include/c++/7/debug/vector:417
#4  0x00007fffe8282bbd in OpenBabel::OpenBabelCallback::setChiral (this=0x7fffffffc8d0, index=0, chirality=Smiley::AntiClockwise, 
    chiralNbrs=std::__debug::vector of length 4, capacity 4 = {...}) at /home/julien/projects/openbabel/src/formats/smileyformat.cpp:140
#5  0x00007fffe8286e39 in Smiley::Parser<OpenBabel::OpenBabelCallback>::processStereochemistry (this=0x7fffffffc7b0)
    at /home/julien/projects/openbabel/src/formats/smiley.h:2656
#6  0x00007fffe828475f in Smiley::Parser<OpenBabel::OpenBabelCallback>::parse (this=0x7fffffffc7b0, 
    str="[C@H]1([C@@H]([C@H]([C@@H]([C@H]([C@@H]1OP(=O)(O)O)O)OP(=O)(O)O)OP(=O)(O)O)O)O\tInositol_trisphosphate") at /home/julien/projects/openbabel/src/formats/smiley.h:2717
#7  0x00007fffe827fb4b in OpenBabel::SmileyFormat::ReadMolecule (this=0x7fffe84b6af0 <OpenBabel::theSmileyFormat>, pOb=0x55555579f1f0, pConv=0x7fffffffe470)
    at /home/julien/projects/openbabel/src/formats/smileyformat.cpp:364
#8  0x00007ffff757896b in OpenBabel::OBMoleculeFormat::ReadChemObjectImpl (pConv=0x7fffffffe470, pFormat=0x7fffe84b6af0 <OpenBabel::theSmileyFormat>)
    at /home/julien/projects/openbabel/src/obmolecformat.cpp:98

This patch prevents from the crash but is it ok or does it just hide the pb?
diff --git a/src/formats/smileyformat.cpp b/src/formats/smileyformat.cpp
index c53a62d7..4870803b 100644
--- a/src/formats/smileyformat.cpp
+++ b/src/formats/smileyformat.cpp
@@ -137,7 +137,7 @@ namespace OpenBabel
       //print_vector("chiralNbrs", chiralNbrs);
 
       unsigned long center = indices[index] - 1;
-      unsigned long from = indices[chiralNbrs[0]] - 1;
+      unsigned long from = (chiralNbrs[0] == Smiley::implicitHydrogen())?OBStereo::ImplicitRef:indices[chiralNbrs[0]] - 1;
       std::vector<unsigned long> refs(chiralNbrs.size() - 1);
       for (std::size_t i = 0; i < refs.size(); ++i)
         if (chiralNbrs[i + 1] == Smiley::implicitHydrogen())

**Comment by baoilleach** [comment]
We should remove this format, as it duplicates smi and I did not update it
in the implicit H rewrite.

**Comment by serval2412** [comment]
@baoilleach: I can try to submit a patch to remove all that concerns smy if you haven't begun to.

**Comment by baoilleach** [comment]
I think that makes sense, but probably we should give a heads up to @timvdm. The idea is that we should move the nice error reporting from smiley into the main smiles parser. But right now, it is better to just remove it as the codebase between the two parsers has diverged and I can't maintain both.
