### ISSUE TITLE
NWChemOutputFormat problem

### ISSUE THREAD

**Issue by PyMadChem** [openbabel/openbabel#347]
I've compiled openbabel on my Fedora 24 and have some problems with NWChem .out file format. If I use
`babel -inwo nwfile.out -oxyz`
I receive segFault:
```
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
*** Error in `/usr/bin/babel': free(): invalid pointer: 0x00007fffe1163350 ***
======= Backtrace: =========
/usr/lib64/libc.so.6(+0x7566b)[0x7ffff7a8c66b]
/usr/lib64/libc.so.6(+0x7de0a)[0x7ffff7a94e0a]
/usr/lib64/libc.so.6(cfree+0x4c)[0x7ffff7a9836c]
/usr/lib/openbabel/2.4.0/nwchemformat.so(_ZN9OpenBabel18NWChemOutputFormat15ReadCoordinatesEPSiPNS_5OBMolE+0x1ff)[0x7fffe0f5ae5f]
/usr/lib/openbabel/2.4.0/nwchemformat.so(_ZN9OpenBabel18NWChemOutputFormat12ReadMoleculeEPNS_6OBBaseEPNS_12OBConversionE+0x1ba)[0x7fffe0f5c82a]
/usr/lib/libopenbabel.so.4(_ZN9OpenBabel16OBMoleculeFormat18ReadChemObjectImplEPNS_12OBConversionEPNS_8OBFormatE+0xd44)[0x7ffff7754ae4]
/usr/lib/libopenbabel.so.4(_ZN9OpenBabel12OBConversion7ConvertEv+0x1d5)[0x7ffff76f9a35]
/usr/lib/libopenbabel.so.4(_ZN9OpenBabel12OBConversion7ConvertEPSiPSo+0xa9)[0x7ffff76ff5f9]
/usr/lib/libopenbabel.so.4(_ZN9OpenBabel12OBConversion11FullConvertERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EERS7_SA_+0x1f71)[0x7ffff7701671]
/usr/bin/babel(main+0xacb)[0x402d9b]
/usr/lib64/libc.so.6(__libc_start_main+0xf1)[0x7ffff7a37731]
/usr/bin/babel(_start+0x29)[0x403429]

```
In GDB:
```
(gdb) backtrace
#0  0x00007ffff7a4b6f5 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff7a4d2fa in __GI_abort () at abort.c:89
#2  0x00007ffff7a8c670 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff7ba3060 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff7a94e0a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>, str=0x7ffff7ba09a3 "free(): invalid pointer", action=3) at malloc.c:5004
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:3865
#5  0x00007ffff7a9836c in __GI___libc_free (mem=<optimized out>) at malloc.c:2966
#6  0x00007fffe0f5ae5f in OpenBabel::NWChemOutputFormat::ReadCoordinates (this=this@entry=0x7fffe1163350 <OpenBabel::theNWChemOutputFormat>, ifs=ifs@entry=0x63b450, molecule=molecule@entry=0x6dca40)
    at /home/madchem/openbabel-2.3.2/openbabel/src/formats/nwchemformat.cpp:237
#7  0x00007fffe0f5c82a in OpenBabel::NWChemOutputFormat::ReadMolecule (this=0x7fffe1163350 <OpenBabel::theNWChemOutputFormat>, pOb=<optimized out>, pConv=0x7fffffffd9c0)
    at /home/madchem/openbabel-2.3.2/openbabel/src/formats/nwchemformat.cpp:1001
#8  0x00007ffff7754ae4 in OpenBabel::OBMoleculeFormat::ReadChemObjectImpl (pConv=0x7fffffffd9c0, pFormat=0x7fffe1163350 <OpenBabel::theNWChemOutputFormat>)
    at /home/madchem/openbabel-2.3.2/openbabel/src/obmolecformat.cpp:105
#9  0x00007ffff76f9a35 in OpenBabel::OBConversion::Convert (this=this@entry=0x7fffffffd9c0) at /home/madchem/openbabel-2.3.2/openbabel/src/obconversion.cpp:545
#10 0x00007ffff76ff5f9 in OpenBabel::OBConversion::Convert (this=this@entry=0x7fffffffd9c0, is=is@entry=0x7fffffffd440, os=os@entry=0x0) at /home/madchem/openbabel-2.3.2/openbabel/src/obconversion.cpp:481
#11 0x00007ffff7701671 in OpenBabel::OBConversion::FullConvert (this=this@entry=0x7fffffffd9c0, FileList=std::vector of length 1, capacity 1 = {...}, OutputFileName="", 
    OutputFileList=std::vector of length 0, capacity 0) at /home/madchem/openbabel-2.3.2/openbabel/src/obconversion.cpp:1486
#12 0x0000000000402d9b in main (argc=4, argv=0x7fffffffde38) at /home/madchem/openbabel-2.3.2/openbabel/tools/babel.cpp:355
```

On #11 
```
#11 0x00007ffff7701671 in OpenBabel::OBConversion::FullConvert (this=this@entry=0x7fffffffd9c0, FileList=std::vector of length 1, capacity 1 = {...}, OutputFileName="", 
    OutputFileList=std::vector of length 0, capacity 0) at /home/madchem/openbabel-2.3.2/openbabel/src/obconversion.cpp:1486
1486	        Count = Convert(pIs,pOs);
(gdb) print Count
$10 = 0
(gdb) print pIs
$11 = (std::istream *) 0x7fffffffd440
(gdb) print pOs
$12 = (std::ostream *) 0x0
```

If I run babel with MALLOC_CHECK_=0 option, it returns incredible coordinates:
```
C  2383367619443439358628085534435951484985966335537686153454449311119641711161195787986102308560524737376490881441551405881409134860026803105922878818997196323810020847303801662603264.000005293718799194156201624522750951791026190211383653590616819402448208770972725595107281919883225314304485639551491401699784679932004404780327973727577176088592599593831824403548078080.0000028801328052341916883577366166980692758933211352106533040108637850410211750239490120425566357677879356394167769017382999881432344971686409537666222765371253507842349136495931824133520845731211413113200153857785593856.00000
N  134449888432409520514217828206644866583253708636304343204479030725881842830476830425089973527586643602284893274103402634450902378179996813199632862145883687354368.00000        0.00000213780573330512203040252175269412003704991197930050743987342008143637097215976590939208056295596749936647144818290948586080217095742100693647766380178206527324160.00000
H  1626910212712747097149502115432000792146070823736040731786422074374628235914087471411806074930762366214040341839150183584081860195903589550725188376732421865596283787163264937215935351622896452561128711047333113768181760.00000       -2.96222        0.66705
H          0.00000        0.00000        0.00000
H         -1.09625       -2.78834       -0.84577
O          1.18771       -0.87566        0.39401
O         -1.03268       -0.60822        0.46385
P         -0.02506        2.44937       -0.13352
H         -0.64137        1.22093       -0.00907
H          1.26031        2.27358       -0.60397
H          0.01681        3.06992        0.00000
```

**Comment by baoilleach** [comment]
I think we will need the input file.

**Comment by PyMadChem** [comment]
[nwfile.txt](https://github.com/openbabel/openbabel/files/482508/nwfile.txt)

Please, change extension to .out

**Comment by PyMadChem** [comment]
@serval2412 actually, [this](https://github.com/openbabel/openbabel/commit/52cea818bf68f8a2d3c48d55d00c2f8b7da25e4c#diff-20022433d332b8e34c28d3dc6f67b9c5) commit fixed this issue. So this bug is closed, I guess.
